import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Lato } from "next/font/google";
import Header from './component/header/Header';
import Footer from './component/footer/Footer';


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // optional: specify weights
  display: "swap",        // recommended
});


const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"], // optional: specify weights
  display: "swap",        // recommended
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ${geistSans.variable} ${geistMono.variable} */}
      <body
        className={` ${roboto.className} antialiased bg-white text-black`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
